# =============================================================================
# GitHub Actions: Security Scan with Rediver Agent
# =============================================================================
# Copy this file to your repository: .github/workflows/security-scan.yml
#
# Features:
# - Runs on push and pull requests
# - Uses rediver-agent:ci Docker image
# - Auto-detects PR context for diff-based scanning
# - Creates inline PR comments for findings
# - Uploads SARIF results to GitHub Security tab
# - Supports all scanners: semgrep, gitleaks, trivy
# =============================================================================

name: Security Scan

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      tools:
        description: 'Scanners to run (comma-separated)'
        required: false
        default: 'semgrep,gitleaks,trivy'
      verbose:
        description: 'Enable verbose output'
        required: false
        default: 'true'
        type: boolean

# Prevent duplicate runs
concurrency:
  group: security-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write  # For SARIF upload
      pull-requests: write    # For PR comments

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for diff-based scanning

      - name: Run Rediver Security Scan
        uses: docker://ghcr.io/rediverio/rediver-agent:ci
        with:
          args: >-
            -tools ${{ github.event.inputs.tools || 'semgrep,gitleaks,trivy' }}
            -target .
            -auto-ci
            -comments
            -push
            ${{ github.event.inputs.verbose == 'true' && '-verbose' || '' }}
            -json
            -output /github/workspace/results.json
            -sarif
            -sarif-output /github/workspace/results.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Required: Push results to Rediver platform
          REDIVER_API_URL: ${{ secrets.REDIVER_API_URL }}
          REDIVER_API_KEY: ${{ secrets.REDIVER_API_KEY }}

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: results.sarif
          category: rediver-security-scan

      - name: Upload scan results artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-scan-results
          path: |
            results.json
            results.sarif
          retention-days: 30

      - name: Check for critical findings
        if: always()
        run: |
          if [ -f results.json ]; then
            CRITICAL=$(cat results.json | jq '[.findings[] | select(.severity == "critical")] | length')
            HIGH=$(cat results.json | jq '[.findings[] | select(.severity == "high")] | length')
            echo "Critical findings: $CRITICAL"
            echo "High findings: $HIGH"
            if [ "$CRITICAL" -gt 0 ]; then
              echo "::error::Found $CRITICAL critical security findings!"
              exit 1
            fi
          fi

  # Optional: Separate job for container scanning
  container-scan:
    name: Container Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: security-scan

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build container image
        run: |
          if [ -f Dockerfile ]; then
            docker build -t ${{ github.repository }}:${{ github.sha }} .
          else
            echo "No Dockerfile found, skipping container scan"
            exit 0
          fi

      - name: Scan container with Trivy
        uses: docker://ghcr.io/rediverio/rediver-agent:ci
        with:
          args: >-
            -tool trivy-image
            -target ${{ github.repository }}:${{ github.sha }}
            -json
            -output /github/workspace/container-results.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload container scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: container-scan-results
          path: container-results.json
